### PR TITLE
Update PerimeterOfParallelogram.java

### PR DESCRIPTION
**Pull request by mohit01-beep**
your program wasn't printing perimeter of parallelogram it was just add all the input and store in perimeter.
formula of perimeter of parallelogram is 2(a+b)
so i've changed some lines and it's working fine now :)

### CODE REVIEW

**Comment by irsayvid** [comment]
Hey I completely got your pov but we're doing the same 2*(l+b) for rectangle so thought to do it differently for a quadrilateral with 4 unequal sides.
Appreciate your contribution and since it doesn't have a specification in the question...I'm going with the previous one

**Comment by mohit01-beep** [comment]
Actually I thought your repository will valid for hacktoberfest too that's
why I thought to give it a try but it says project not participating

**Comment by irsayvid** [comment]
Hey! If you're looking for contribution in hacktoberfest....checkout project sirius...I'm the maintainer for that....
Any contribution which adds value to that will be highly appreciated be it frontend or backend

**Comment by mohit01-beep** [comment]
Hey I checked that site it looks good and I don't knw that much so I don't
wanna mess it up but I found one bug in that site in contacts section

**Comment by irsayvid** [comment]
It would be great if you can open an issue giving a clear description of the bug

**Comment by mohit01-beep** [comment]
Okay 😁

**Pull request closed without merging**
